name: CI

on:
  push:
    branches: [upload-binary]

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.5"]
        ghc: ["8.10.3"]

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2.0.1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v3.0.11
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc

    - name: Install
      run: |
        stack install --system-ghc --local-bin-path=.

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: stan
          path: ./stan
